[build]
  command = "npx expo export -p web"
  publish = "dist"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "EXPO_PUBLIC_GEMINI_API_KEY"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
